backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

publish_mode: editorial_workflow
local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: trainings
    label: Trainings
    label_singular: 'Training'
    folder: content/trainings
    identifier_field: uniqueName
    create: true
    fields:
      - label: Unique Name
        name: uniqueName
        widget: string
        pattern: ['^(?!admin$)[a-z0-9\-]+$', "Must have only lowercase english letters, numbers and dashes. The name 'admin' is not allowed"]
        hint: "Only lowercase english letters, numbers and dashes are allowed."
        default: ""
      - label: Title
        name: title
        widget: string
        default: ""

# editorial_workflow:
#   publish_mode: editorial_workflow
#   roles:
#     - name: "admin"
#       label: "Admin"
#       permissions:
#         - "publish"

# create: Allows users to create new content in the CMS.
# read: Allows users to view existing content in the CMS.
# update: Allows users to edit existing content in the CMS.
# delete: Allows users to delete existing content in the CMS.
# publish: Allows users to approve and publish changes to content in the CMS.
# unpublish: Allows users to unpublish content in the CMS.
# revert: Allows users to revert changes to content in the CMS.
# admin: Allows users to access the CMS settings and configurations.