backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

publish_mode: editorial_workflow
local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: trainings
    label: Trainings
    label_singular: 'Training'
    folder: content/trainings
    identifier_field: uniqueName
    create: true
    fields:
      - label: Unique Name
        name: uniqueName
        widget: string
        pattern: ['^[a-z0-9\-]+$', "Must have only lowercase english letters, numbers and dashes"]
        hint: "A version with exactly the same UNIQUE NAME is needed. Only lowercase english letters, numbers and dashes are allowed."
      - label: Title
        name: title
        widget: string
  - name: versions
    label: Versions
    label_singular: 'Version'
    folder: content/versions
    identifier_field: uniqueName
    create: true
    fields:
      - label: Unique Name
        name: uniqueName
        widget: string
        pattern: ['^[a-z0-9\-]+$', "Must have only lowercase english letters, numbers and dashes. Only lowercase english letters, numbers and dashes are allowed."]
        hint: "A training with exactly the same UNIQUE NAME is needed"
      - label: release date
        name: releaseDate
        widget: date
        format: 'HH:mm - MMM Do YY'
        date_format: true
        time_format: true
