backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

publish_mode: editorial_workflow
local_backend: true
media_folder: static/img/${trainingToBuild}
public_folder: /img/${trainingToBuild}

collections:
  - name: trainings
    label: Trainings
    label_singular: 'Training'
    folder: content/trainings
    identifier_field: uniqueName
    filter: {field: "uniqueName", value: "${trainingToBuild}"}
    create: false
    fields:
      - label: Unique Name
        name: uniqueName
        widget: hidden
        default: ""
      - label: Title
        name: title
        widget: string
        default: ""
      - label: "Active"
        name: "isActive"
        widget: "boolean"
        default: true
      - label: Sections
        name: sections
        minimize_collapsed: true
        widget: "list"
        fields:
          - { label: Section Title, name: sectionTitle, widget: string, default: "", unique: true }
          - { label: "Active", name: "isActive", widget: "boolean", default: true }
          - { label: pages,
              name: pages,
              minimize_collapsed: true,
              widget: list,
              fields: [
                { label: "Page Title", name: "pageTitle", widget: "string", default: "", hint: "It will not appear in the Slide. It will be used only for creation of URL" },
                { label: "Active", name: "isActive", widget: "boolean", default: true },
                { label: "Body", name: "body", widget: "markdown",default: "" }
              ]
            }

